let formData = [
    "Ctriticism will obviously upset the person who receives the criticism.",
    "It is best to give up my own interests in order to please other people.",
    "I need other people's approval in order to be happy.",
    "If someone important to me expects me to do something, then I really should do it.",
    "My value as a person depends greatly on what others think of me.",
    "I cannot find happiness without being loved by another person.",
    "If others dislike you, you are bound to be less happy.",
    "If people wwhom I care about reject me, it means there is something wrong with me.",
    "If a person I love does not love me, it means I am unlovable.",
    "Being isolated from others is bound to lead to unhappiness.",
    "If I am to be a worthwhile person, I must be truly outstanding in at least one major respect.",
    "I must be a useful, productive, creative person or life has no purpose.",
    "People who have good ideas are more worthy than those who do not.",
    "If I do not do as well as other people, it means I am inferior.",
    "If I fail at my work, then I am a failure as a person.",
    "If you cannot do something well, there is little point in doing it at all.",
    "It is shameful for a person to display his weaknesses.",
    "A person should try to be the best at everything he undertakes.",
    "I should be upset if I make a mistake.",
    "If I don't set the highest standards for myself, I am likely to end up a second-rate person.",
    "If I stronlgy believe I deserve something, I have reason to expect that I should get it.",
    "It is necessary to become frustrated if you find obstacles to getting what you want.",
    "If I put other people's needs before my own, they should help me when I need something from them.",
    "If  I am a good husband/wife, then my spouse is bound to love me.",
    "If I do nice things for someone, I can anticipate that they will respect me and treat me just as well as I treat them.",
    "I should assume responsibility for how people feel and behave if they are close to me.",
    "If I criticize the way someone does something and they become angry or depressed, this means I have upset them",
    "To be a good, worthwhile, moral person, I must try to help everyone who needs it.",
    "If a child is having emotional or behavioral difficulties, this shows that the child's parents have failed, in some important respect.",
    "I should be able to please everybody.",
    "I cannot expect to control how I feel when something bad happens.",
    "There is no point in trying to change upsetting emotions because they are a valid and inevitable part of daily life.",
    "My moods are primarily created by factors that are largely beyond my control, such as the past, or body chemistry, or hormone cycles, or biorhythms, or change, or fate.",
    "My happiness is largely dependant on what happens to me.",
    "People who have the marks of success (good looks, social status, wealth, or fame) are bound to be happier than those who do not."
];

let categories = ["Approval", "Love", "Achievement", "Perfectionism", "Entitlement", "Omnipotence", "Autonomy"];

let descriptions = [
    "The first five attitudes on the DAS test probe your tendency to measure your self-esteem based on how people react to you and what they think of you. A positive score between zero and ten indicates you are independent, with a healthy sense of your own worth even when confronted with criticism and disapproval. A negative score between zero and minus ten indicates you are excessively dependent because you evaluate yourself through other people’s eyes. If someone insults you or puts you down, you automatically tend to look down on yourself. Since your emotional well-being is exquisitely sensitive to what you imagine people think of you, you can be easily manipulated, and you are vulnerable to anxiety and depression when others criticize you or are angry with you.",
    "The second five attitudes on the test assess your tendency to base your worth on whether or not you are loved. A positive score indicates you see love as desirable, but you have a wide range of other interests you also find gratifying and fulfilling. Hence, love is not a requirement for your happiness or self-esteem. People are likely to find you attractive because you radiate a healthy sense of self-love and are interested in many aspects of living.\n" +
    "A negative score indicates you are a “love junkie.” You see love as a “need” without which you cannot survive, much less be happy. The closer your score is to minus ten, the more dependent on love you are. You tend to adopt inferior, put-down roles in relationships with people you care about for fear of alienating them. The result of this, more often than not, is that they lose respect for you and consider you a burden because of your attitude that without their love you would collapse. As you sense that people drift away from you, you become gripped by a painful, terrifying withdrawal syndrome. You realize you may not be able to “shoot up” with your daily dose of affection and attention. You then become consumed by the driving compulsion to “get love.” Like most junkies, you may even resort to coercive, manipulative behavior to get your “stuff.” Ironically, your needy, greedy love addiction drives many people away, thus intensifying your loneliness.",
    "Your score on attitudes 11 through 15 will help you measure a different type of addiction. A negative score indicates you are a workaholic. You have a constricted sense of your own humanity, and you see yourself as a commodity in the marketplace. The more negative your score, the more your sense of self-worth and your capacity for joy are dependent on your productivity. If you go on vacation, if your business slumps, if you retire or become ill and inactive, you will be in danger of an emotional crash. Economic and emotional depressions will seem identical to you. A positive score, in contrast, indicates that you enjoy creativity and productivity, but do not see them as an exclusive or necessary road to self-esteem and satisfaction.",
    "Items 16 through 20 measure your tendency to perfectionism. A negative score indicates you are hooked on searching for the Holy Grail. You demand perfection in yourself—mistakes are taboo, failure is worse than death, and even negative emotions are a disaster. You’re supposed to look, feel, think, and behave superbly at all times. You sense mat being less than spectacular means burning in the flames of hell. Although you drive yourself at an intense pace, your satisfactions are meager. Once you do achieve a goal, another more distant goal instantly replaces it, so you never experience the reward of getting to the top of the mountain. Eventually you begin to wonder why the promised payoff from all your effort never seems to materialize. Your life becomes a joyless, tedious treadmill. You are living with unrealistic, impossible personal standards, and you need to reevaluate them. Your problem does not lie in your performance, but in the yardstick you use to measure it. If you bring your expectations in line with reality, you will be regularly pleased and rewarded instead of frustrated.\n" +
    "A positive score suggests you have die capacity to set meaningful, flexible, appropriate standards. You get great satisfaction from processes and experiences, and you are not exclusively fixated on outcomes. You don’t have to be outstanding at everything, and you don’t always have to “try your best.” You don’t fear mistakes, but you see them as golden opportunities to learn and to endorse your humanity. Paradoxically, you are likely to be much more productive than your perfectionistic associates because you do not become compulsively preoccupied with detail and correctness. Your life is like a flowing river or a geyser compared with your rigid perfectionistic friends who appear more like icy glaciers.",
    "Attitudes 21 through 25 measure your sense of “entitlement.” A negative score indicates that you feel “entitled” to things—success, love, happiness, etc. You expect and demand that your wants be met by other people and by the universe at large because of your inherent goodness or hard work. When this does not happen—as is often the case—you are locked into one of two reactions. Either you feel depressed and inadequate or you become irate. Thus, you consume enormous amounts of energy being frustrated, sad, and mad. Much of the time you see life as a sour, rotten experience. You complain loudly and often, but you do little to solve problems. After all, you’re entitled to have them solved, so why should you have to put out any effort? As a result of your bitter, demanding attitudes, you invariably get far less of what you want from life.\n" +
    "A positive score suggests you don’t feel automatically entitled to things, so you negotiate for what you want and often get it. Because of your awareness that other people are unique and different, you realize there is no inherent reason why things should always go your way. You experience a negative outcome as a disappointment but not a tragedy because you are a percentage player, and you don’t expect perfect reciprocity or “justice” at all times. You are patient and persistent, and you have a high frustration tolerance. As a result, you often end up ahead of the pack.",
    "Attitudes 26 through 30 measure your tendency to see yourself as the center of your personal universe and to hold yourself responsible for much of what goes on around you. A negative score indicates you often make the personalization error discussed in Chapters 3 and 6. You blame yourself inappropriately for the negative actions and attitudes of others who are not really under your control. Consequently, you are plagued by guilt and self-condemnation. Paradoxically, the attitude that you should be omnipotent and all-powerful cripples you and leaves you anxious and ineffectual.\n" +
    "A positive score, in contrast, indicates you know die joy that comes from accepting that you are not the center of the universe. Since you are not in control of other adults, you are not ultimately responsible for them but only for yourself. This attitude does not isolate you from others. Quite the opposite is true. You relate to people effectively as a friendly collaborator, and you are not threatened when they disagree with your ideas or fail to follow your advice. Because your attitude gives people a sense of freedom and dignity, you paradoxically become a human magnet. Others often want to be close to you because you have relinquished any attempt to control them. People frequently listen to and respect your ideas because you do not polarize them with an angry insistence they must agree with you. As you give up your drive for power, people repay you by making you a person of influence. Your relationships with your children and friends and associates are characterized by mutuality instead of dependency. Because you don’t try to dominate people, they admire, love, and respect you.",
    "Items 31 through 35 measure your autonomy. This refers to your ability to find happiness within yourself. A positive score indicates that all your moods are ultimately the children of your thoughts and attitudes. You assume responsibility for your feelings because you recognize they are ultimately created by you. This sounds as if you might be lonely and isolated because you realize that all meaning and feelings are created only in your head. Paradoxically, however, this vision of autonomy frees you from the petty confines of your mind and delivers the world to you with a full measure of all the satisfaction, mystery, and excitement that it can offer.\n" +
    "A negative score suggests you are still trapped in the belief that-your potential for joy and self-esteem comes from the outside. This puts you at a great disadvantage because everything outside is ultimately beyond your control. Your moods end up the victim of external factors. Do you want this? If not, you can eventually free yourself from this attitude as surely as a snake sheds its skin, but you will have to work at it with the various methods outlined in this book. When it’s finally your turn to experience the transformation to autonomy and personal responsibility, you will be amazed—or awestruck—or pleased—or delightfully overwhelmed. It’s well worth a major personal commitment."
]
